# Generated by Django 3.2.19 on 2023-06-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
