# Generated by Django 3.2.19 on 2023-06-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20230615_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
        migrations.AlterField(
            model_name='image',
            name='position_number',
            field=models.IntegerField(null=True),
        ),
    ]
