# Generated by Django 4.2.2 on 2023-06-17 11:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_remove_place_imgs_alter_image_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image", options={"ordering": ("position_number",)},
        ),
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=tinymce.models.HTMLField(verbose_name="Краткое описание"),
        ),
    ]
