# Generated by Django 4.2.2 on 2023-07-01 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0014_alter_image_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(
                default=uuid.uuid1, max_length=250, verbose_name="Локация"
            ),
        ),
    ]
